version: '3'

services:
  asset:
    container_name: asset
    build:
      context: asset/php-apache
    volumes:
      # Chỉ mount các thư mục cần thiết để giảm overhead
      - ../sconnect-asset:/var/www/html:cached
      - ../sconnect-asset/storage:/var/www/html/storage
      - ../sconnect-asset/bootstrap/cache:/var/www/html/bootstrap/cache
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.asset.rule=Host(`asset.local.test`)"
      - "traefik.http.services.asset.loadbalancer.server.port=80"
    networks:
      - webgateway
    restart: always
    # Giới hạn tài nguyên cho container để tránh việc tiêu tốn quá nhiều tài nguyên
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  db_asset:
    image: mysql:latest
    container_name: db_asset
    environment:
      MYSQL_ROOT_PASSWORD: 'Asset123#@!'
      MYSQL_DATABASE: asset
      MYSQL_USER: asset
      MYSQL_PASSWORD: 'Asset123#@!'
    ports:
      - "3308:3306"
    volumes:
      - db_data_asset:/var/lib/mysql
    networks:
      - webgateway
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G


  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
      - "6379:6379"  # Cổng mặc định của Redis
    networks:
      - webgateway

volumes:
  db_data_asset:

networks:
  webgateway:
    driver: bridge
