version: '3'

services:
  proxy:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"  # Giao diện quản lý tại http://localhost:8080
      - "--providers.docker=true"  # Kích hoạt Docker provider
      - "--entrypoints.web.address=:80"  # HTTP entrypoint trên cổng 80
      - "--log.level=DEBUG"  # Mức log là DEBUG
    networks:
      - webgateway
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  asset:
    build:
      context: asset/php-apache
    volumes:
      - ../asset:/var/www/html
    ports:
      - "8084:80"
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:asset.local"
      - "traefik.backend=user"
    networks:
      - webgateway
      - web
    restart: always

  eoffice:
      build:
        context: eOffice/php-apache
      volumes:
        - ../eOffice:/var/www/html
      ports:
        - "8085:80"
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:eOffice.local"
        - "traefik.backend=user"
      networks:
        - my_network
      restart: always

  db_office:
    image: mysql:latest
    container_name: mysql-office
    environment:
      MYSQL_ROOT_PASSWORD: 'Office123#@!'
      MYSQL_DATABASE: eoffice
      MYSQL_USER: office
      MYSQL_PASSWORD: 'Office123#@!'
    ports:
      - "3307:3306"
    volumes:
      - db_data_office:/var/lib/mysql
    networks:
      - my_network

  db_asset:
    image: mysql:latest
    container_name: mysql-asset
    environment:
      MYSQL_ROOT_PASSWORD: 'Asset123#@!'
      MYSQL_DATABASE:
      MYSQL_USER: asset
      MYSQL_PASSWORD: 'Asset123#@!'
    ports:
      - "3308:3306"
    volumes:
      - db_data_asset:/var/lib/mysql

volumes:
  db_data_office:
  db_data_asset:

networks:
  webgateway:
    driver: bridge
  web:
    external:
      name: traefik_webgateway
  my_network: