services:
  asset:
    container_name: asset
    build:
      context: asset/php-apache
    volumes:
      - ../asset:/var/www/html
    ports:
      - "8084:80"
      - "9004:9004"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.asset.rule=Host(`asset.local.test`)"
      - "traefik.http.services.asset.loadbalancer.server.port=80"
    networks:
      - webgateway
      - web
    restart: always

  db_asset:
    image: mysql:latest
    container_name: db_asset
    environment:
      MYSQL_ROOT_PASSWORD: 'Asset123#@!'
      MYSQL_DATABASE: asset
      MYSQL_USER: asset
      MYSQL_PASSWORD: 'Asset123#@!'
    ports:
      - "3308:3306"
    volumes:
      - db_data_asset:/var/lib/mysql
    networks:
      - webgateway
      - web

volumes:
  db_data_asset:

networks:
  webgateway:
    driver: bridge
  web:
    external: true
    name: traefik_webgateway